image: docker

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: ysfdnz/logo-project:latest
  AWS_REGION: eu-central-1
  CLUSTER_NAME: tf-logo-devops
  SERVICE_NAME: ecs-service
services:
  - docker:dind
build:
  stage: build
  script:
    - echo $DOCKER_HUB_PASS | docker login --username $DOCKER_HUB_USER --password-stdin
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE .
    - echo "Pushing Docker image to your Docker registry..."
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  script:
    - apk add --no-cache curl python3 py3-pip
    - pip install awscli
    - echo "Deploying to AWS..."
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
    - echo "Deploying to AWS ECS Fargate..."
    - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
